### ISSUE TITLE
[MV] [folder pictures] incorrect file names given by exe

### ISSUE THREAD

**Issue by EccentricSatyr** [gimmer/RPG-Maker-MV-Plugins#1]
I am trying to use your folder pictures plugin to organize my images. I downloaded and installed from itch.io ... then ran your folderPictureHelper.exe inside my picture folder. (using a batch file)

Batch File code here: `folderPictureHelper.exe "MyPathFileToProject\img\pictures"` 
(I removed my system path)
(folderPictureHelper.exe is inside the picture folder)

The resulting image files are correctly created, however the file names use - instead of _ so your code in the plugin does not recognize them (resulting in an error when playing)

File Tested On: `MyPathFileToProject\img\pictures\test\test2\Night.png`
File Created by program: `MyPathFileToProject\img\pictures\folderpicture_test-test2-Night.png`

Other than the odd instances of the - character instead of the _ character, everything else seems to work (the plugin works if I create the files manually)

I know that not many people use MV anymore, but could you either update the plugin to accept the - or edit the exe to give the correct file names?

**Comment by gimmer** [comment]
I replaced the .exe with a new one. No idea why I mixed up the two characters between the plugin and the helper program beyond my usual levels of lack of paying attention to my own work

**Comment by EccentricSatyr** [comment]
That has fixed the image name problems :) Thanks

I have found one small issue that may not be an issue at all (especially as your "helper" images are 0kb) ... but when I delete the helper pictures (to make the image folder a little easier to see in), the console returns an error:

`Failed to load resource: net::ERR_FILE_NOT_FOUND folderpicture_test2_test3_Night.png`

The image loads perfectly, your plugin works perfectly ... I think I just need to find out where in the js the system is wanting the original file and either remove that check (risky) or add your code there too somehow.

As this is probably not something most users will want, feel free to close this issue (as it definitely is fixed) ... I am going to troll the js to see if I can find the part where it is asking for the file that I am not using now.

**Comment by EccentricSatyr** [comment]
I think I found what is causing the request for the old image name (before your plugin shows the correct image) ... it is the decoder.

rpg_core.js:1667

Not going to try and even look at anything dealing with the decoder ... so I am just going to leave the fake images in place.

I definitley isn't your plugin though as the stack it gave me doesn't even reference anything that seems close to the bitmap loader.

```
GET chrome-extension://neengnciboafjlmcklcomcfcchiihfng/img/pictures/folderpicture_test2_test3_Night.png net::ERR_FILE_NOT_FOUND
Image (async) 
  | Bitmap._requestImage | @ | rpg_core.js:1686
  | Bitmap.startRequest | @ | rpg_core.js:1706
  | RequestQueue.update | @ | rpg_core.js:594
  | ImageManager.update | @ | rpg_managers.js:1088
  | SceneManager.updateManagers | @ | rpg_managers.js:1992
  | SceneManager.update | @ | rpg_managers.js:1906
  | requestAnimationFrame (async) |   |  
  | SceneManager.requestUpdate | @ | rpg_managers.js:1896
  | SceneManager.updateMainNoFpsSynch | @ | YEP_FpsSynchOption.js:212
  | SceneManager.updateMain | @ | YEP_FpsSynchOption.js:203
  | SceneManager.update | @ | rpg_managers.js:1907
  | requestAnimationFrame (async) |   |  
```

**Comment by EccentricSatyr** [comment]
I did just package my game using the default encryption ... just to double check your plugin still worked ... and it does. (even if you delete the encrypted "temp" files too)

So def not an issue anymore.

(Not sure about custom encryption plugins though ... but I don't use them so yay me)
