### ISSUE TITLE
Plugin Command example?

### ISSUE THREAD

**Issue by noidavoid** [gimmer/RPG-Maker-MV-Plugins#2]
> ===Command===
> AddTempText
> ===Params===
> x: Where on the x to put the text. Can be a number or an eval'd string (e.g. Graphics.boxWidth/2)
> y: Where on the y to put the text. Can be a number or an eval'd string (e.g. Graphics.boxHeight/2)
> text: the text you want to show

I'm trying to get this to work but none of the ways I use this plugin command works for me. Could you please provide an example?
I've tried AddTempText 100, 100, "hello", 5
I've tried AddTempText 100 100 "hello" 5
I've also tried other variations with no success. What am I doing wrong?

**Comment by gimmer** [comment]
AddTempText 100 100 "Hello" 60 hide

Would add the word hello on the screen for 60 frames (1 second) and then hide it.

**Comment by noidavoid** [comment]
So I was recieving an error at line 360 of Gimmer_TextAnywhere.js. Specifically about the JSON.parse line.
It had nothing to parse in the UI Picture Library so the plugin just didn't work. I added a picture and it appears to be working now.

Thanks by the way. Small bug but all seems good now.

**Comment by gimmer** [comment]
Ah that makes sense. I added that feature later and probably never tested what happens if you aren't using it

**Comment by gimmer** [comment]
I pushed a fixed in 2.9.1
